name: release (PyPI)
 
on:
  push:
    tags:
    - 'v*'
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up env
      run: |
        pip install -e .
    - name: build package
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        user: __token__
        password: ${{ secrets.pypi_api_token }}
        repository_url: https://test.pypi.org/legacy/
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
